version: '3.0'

networks:
  test-network:
    driver: bridge

services:
  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:3000
    networks:
      - test-network
    depends_on:
      - backend
  
  backend:
    container_name: backend
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    ports:
      - 5000:5000
    networks:
      - test-network
    
    