name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.11

  #     - name: Install and configure Poetry
  #       uses: snok/install-poetry@v1

  #     # go into the project directory
  #     - name: Run tests
  #       run: |
  #         cd /home/runner/work/demo2/demo2/backend
  #         ls -la
  #         poetry install --no-interaction --no-ansi
  #         poetry run python -B -m pytest

  Deploy:
    # needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          AWS_EC2_HOST_NAME: ${{ secrets.AWS_EC2_HOST_NAME  }}
          AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_USERNAME  }}

        run: |
          echo "$AWS_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_EC2_USERNAME}@${AWS_EC2_HOST_NAME}

          #Now we have got the access of EC2 and we will start the deploy .
          ls -la &&
          git checkout main &&
          git fetch --all &&
          git reset --hard origin/main &&
          git pull origin main &&
          docker-compose build --no-cache &&
          docker-compose up -d

          # remove the key
          rm -f private_key
