name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      # go into the project directory
      - name: Run tests
        run: |
          cd /home/runner/work/demo2/demo2/backend
          ls -la
          poetry install
          poetry run python -B -m pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the docker compose
        run: docker-compose up -d --build
